### ISSUE TITLE
 6751 - fatal issue with plugin

### ISSUE THREAD

**Issue by robert81** [wpwhitesecurity/admin-notices-manager#66]
User reported the following:

WordPress version 5.9.1 Current theme: ColorMag Pro (version 3.3.0) Current plugin: Admin Notices Manager (version 1.2.0) PHP version 8.0.16 Error Details ============= An error of type E_ERROR was caused in line 305 of the file /home1/pupilmag/public_html/dailydigest/wp-content/plugins/admin-notices-manager/includes/vendor/jeremyHixon-RationalOptionPages/RationalOptionPages.php. Error message: Uncaught Error: Unknown named parameter $callback in /home1/pupilmag/public_html/dailydigest/wp-content/plugins/admin-notices-manager/includes/vendor/jeremyHixon-RationalOptionPages/RationalOptionPages.php:305 Stack trace: #0 /home1/pupilmag/public_html/dailydigest/wp-includes/class-wp-hook.php(307): RationalOptionPages->admin_menu('') #1 /home1/pupilmag/public_html/dailydigest/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array) #2 /home1/pupilmag/public_html/dailydigest/wp-includes/plugin.php(474): WP_Hook->do_action(Array) #3 /home1/pupilmag/public_html/dailydigest/wp-admin/includes/menu.php(155): do_action('admin_menu', '') #4 /home1/pupilmag/public_html/dailydigest/wp-admin/menu.php(394): require_once('/home1/pupilmag...') #5 /home1/pupilmag/public_html/dailydigest/wp-admin/admin.php(158): require('/home1/pupilmag...') #6 /home1/pupilmag/public_html/dailydigest/wp-admin/plugins.php(10): require_once('/home1/pupilmag...') #7 {main} thrown

Let me know if you require more information from this user. Maybe we should simply send him the latest update and ask him if he can reproduce this. Anyway, just opening the ticket so if this rings a bell, let's fix it. IF not, let's just send them the latest build.

Support ticket: https://secure.helpscout.net/conversation/1804585098/6751/

**Comment by martinkrcho** [comment]
It reminds me of another PHP8 issue we already addressed in 1.3.0.
https://github.com/wpwhitesecurity/admin-notices-manager/issues/57

Let's send the up update (available on Google Drive).
https://drive.google.com/drive/u/1/folders/15ydDa4hNvvXkozHeOIa5QllXJUGpxc7E

**Comment by robert81** [comment]
@martinkrcho the user who reported this problem now tried to upgrade the plugin and said he is getting this error when activating the plugin:

Warning: require(/home1/pupilmag/public_html/exampleschool/wp-content/plugins/admin-notices-manager/vendor/composer/../wpwhitesecurity/select2-wpwhitesecurity/load.php): Failed to open stream: No such file or directory in /home1/pupilmag/public_html/exampleschool/wp-content/plugins/admin-notices-manager/vendor/composer/autoload_real.php on line 76

Fatal error: Uncaught Error: Failed opening required '/home1/pupilmag/public_html/exampleschool/wp-content/plugins/admin-notices-manager/vendor/composer/../wpwhitesecurity/select2-wpwhitesecurity/load.php' (include_path='.:/opt/cpanel/ea-php80/root/usr/share/pear') in /home1/pupilmag/public_html/exampleschool/wp-content/plugins/admin-notices-manager/vendor/composer/autoload_real.php:76 Stack trace: #0 /home1/pupilmag/public_html/exampleschool/wp-content/plugins/admin-notices-manager/vendor/composer/autoload_real.php(59): composerRequire304e4e1b4bd9c34ebc34bb32b0515839('ed8f7d07f343dc9...', '/home1/pupilmag...') #1 /home1/pupilmag/public_html/exampleschool/wp-content/plugins/admin-notices-manager/vendor/autoload.php(7): ComposerAutoloaderInit304e4e1b4bd9c34ebc34bb32b0515839::getLoader() #2 /home1/pupilmag/public_html/exampleschool/wp-content/plugins/admin-notices-manager/admin-notices-manager.php(51): require_once('/home1/pupilmag...') #3 /home1/pupilmag/public_html/exampleschool/wp-admin/includes/plugin.php(2288): include_once('/home1/pupilmag...') #4 /home1/pupilmag/public_html/exampleschool/wp-admin/plugins.php(192): plugin_sandbox_scrape('admin-notices-m...') #5 {main} thrown in /home1/pupilmag/public_html/exampleschool/wp-content/plugins/admin-notices-manager/vendor/composer/autoload_real.php on line 76

The problem here is that there are other people reporting this: https://wordpress.org/support/topic/upgrading-breaks-site/

So I tried the plugin on a vanilla WordPress install. If I try to install it via the repo I get the same error:

![image](https://user-images.githubusercontent.com/3965050/157517058-7e1abf20-d802-4319-ad93-09f3ddc7a3e1.png)

If I install the plugin from the [release on Github](https://github.com/wpwhitesecurity/admin-notices-manager/releases/tag/1.3.0) it works well.

When I compare the files of the plugin from the release and the WordPress repo, they are the same (apart from the readme.txt and the languages folder, but that is ok):

![image](https://user-images.githubusercontent.com/3965050/157517349-eb3b6e09-7ecf-4c5d-9120-c6ce0aaf38fd.png)

Any idea what could be wrong?

**Comment by martinkrcho** [comment]
We added the `select2-for-wordpress`library in 1.3.0. Plugin ZIP needs to be created by running the build script. Downloading it directly from the repo is no longer an option. I will add a new section **Releasing a version update** to the readme file to make it more obvious.

In the meantime, can you please upload the contents of the ZIP from the GitHub releases section to wp.org SVN repo?

**Comment by martinkrcho** [comment]
I updated the readme file in this commit, @robert81 . Please have a look if it's more obvious now ;)

**Comment by robert81** [comment]
My 🤦 on this one.... sorry for the false alarm.
