### ISSUE TITLE
Elementor notices are not displayed in the panel

### ISSUE THREAD

**Issue by robert81** [wpwhitesecurity/admin-notices-manager#68]
More information: https://wordpress.org/support/topic/messages-are-not-displayed-in-the-sliding-notifices-panel/

**Comment by DannyWPWS** [comment]
This appears to be totally fine now 

![image](https://user-images.githubusercontent.com/59394454/217523615-89328566-f0af-4139-84d8-0ac3d3ace109.png)

I think we can close this one @robert81

**Comment by jwjsystem** [comment]
I have checked only the "settings saved" (the only one I could easily reproduce and make show up) and it was not displayed in the admin notices box. -> draws me to the conclusion that there might still be more with this problem. 

This will need more checks definitely. 

![y](https://user-images.githubusercontent.com/92275653/218129680-a816f0ae-ed7f-43cd-897d-200c3a77b561.png)

**Comment by jwjsystem** [comment]
False positive from my side - since that notificatoin was already showing in the wp pannel, all is good. Closing up
