### ISSUE TITLE
Conflict with Loco translations

### ISSUE THREAD

**Issue by robert81** [wpwhitesecurity/admin-notices-manager#70]
https://wordpress.org/support/topic/conflict-with-loco-translate-4/

**Comment by DannyWPWS** [comment]
Wow, loco translate actually use notice classes for there admin areas! Crazy! Should be able to get around this tho

**Comment by jwjsystem** [comment]
@DannyWPWS  Found couple of issues with some link buttons - the one that seems to not be working properly in all scenarios tested is "DELETE" button . 

I've tested all areas of the plugin for possible conflicts with our plugin, here are the outcomes:
1. 
![1](https://user-images.githubusercontent.com/92275653/218125625-da3d7465-3ead-4fb5-b6a3-05794756fe62.png)
2
![2](https://user-images.githubusercontent.com/92275653/218125648-bacdd3e6-19f2-4559-b824-82bf3483990c.png)
3. 
![3](https://user-images.githubusercontent.com/92275653/218125714-4c62b2bc-2c30-4315-9134-e5662692a210.png)
4
![4](https://user-images.githubusercontent.com/92275653/218125736-75554e5c-4b69-4b4c-a2d6-73bcd679020c.png)
5
![5](https://user-images.githubusercontent.com/92275653/218125782-16dcd203-49b7-4000-adff-56a385b023ea.png)

**Comment by jwjsystem** [comment]
@DannyWPWS Found a couple more this time (sorry for the re-opening) it must have slipped through my radar first time.

![1](https://user-images.githubusercontent.com/92275653/218757766-3eadfb6d-04df-495d-89b1-58adc795e058.png)


![2](https://user-images.githubusercontent.com/92275653/218757780-a1251dd8-ebc6-46ed-a5d0-bb492742d258.png)


![3](https://user-images.githubusercontent.com/92275653/218757788-ea8e1c89-12e2-4b56-ab6e-46e4f14b46b1.png)
