### ISSUE TITLE
Small issue with notifications '1' showing up instead of none

### ISSUE THREAD

**Issue by jwjsystem** [wpwhitesecurity/admin-notices-manager#78]
Not sure if this is indeed a feature (to have that '1' for design purposes to indicate a notification pannel), or if it should be removed? 

I reproduced this after hiding all the list of notifications. I was expecting that '1' though to go away.

![w](https://user-images.githubusercontent.com/92275653/218134901-36bed03f-d52a-4537-96f5-0b144aebbd49.png)

**Comment by DannyWPWS** [comment]
@jwjsystem 

Please check this again with the latest build

I was unable to reproduce a problem (the number went to 0) here so if you can, please provide steps I can follow so I can do the same, thanks

**Comment by DannyWPWS** [comment]
Current behaviour https://i.gyazo.com/c97386348bb042a0a91ceb16272f7a1c.mp4

**Comment by jwjsystem** [comment]
@DannyWPWS I will give this one a go again when the build is ready - I might have omitted some extra details - I came across this with other plugins installed (such as Elementor, Loco Translate - the ones for which users have reported some issues),  and that's why most probaby this occured,  because of an interactions.

I will come back if I manage to reproduce again after re-testing on single and multi .  

Thank you!

**Comment by jwjsystem** [comment]
@DannyWPWS Update:

I managed to reproduce again on this test site - the notification number is displayed as "3" for example, but when opening the tab there are "2" displayed.

https://site4.lucian.wpws.org/wp-admin/update-core.php

**Comment by DannyWPWS** [comment]
Noting some details as this is not globally an issue - the count changes based on screen

https://site4.lucian.wpws.org/wp-admin/update-core.php shows 3 in the number, but 2 notices, wheras https://site4.lucian.wpws.org/wp-admin/plugins.php displays 2 in the number which is correct
